### ISSUE TITLE
intensity_normalization not working

### ISSUE THREAD

**Issue by srvparmar** [ALebrun-108/BoxSERS#5]
**Describe the bug**
intensity_normalization is not imported from **boxsers.prprocessing** when reproducing the results using the codes in IDLE SHELL 3.10.6
**To Reproduce**

**Expected behavior**
since normalization did not work...all the figures were generated as is shown on the GitHUB site except the last two!!
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux ubuntu 22.04
 - Browser Firefox

**Smartphone (please complete the following information):**

**Additional context
Jupyter notebooks were not used though!

**Comment by ALebrun-108** [comment]
Hi, 

I'm sorry to hear about your issue. It turns out that I replaced the "intensity_normalization" function with "spectral_normalization" a few months ago. I thought I had replaced it throughout the whole Github, but I overlooked a few typos and I apologize for that. Use "spectral_normalization" instead to resolve this issue. 

Best regards,

Alexis
